### ISSUE TITLE
Major changes of msldap 0.4.0

### ISSUE THREAD

**Issue by fabelx** [zyn3rgy/LdapRelayScan#12]
Changes to [msldap ](https://github.com/skelsec/msldap) break imports in [LdapRelayScan](https://github.com/zyn3rgy/LdapRelayScan).

For example, importing **MSLDAPURLDecoder, MSLDAPClientConnection** from **msldap.commons.url** is not possible since **0.4.0**.

Please update `requirements.txt` with the exact versions of the libraries (**for all dependencies**).

**Comment by mgeeky** [comment]
@fabelx Did you resolve the issue? 
If so, could you please share your `requirements.txt` that I could use? :)

I'm on the audit now and could really use it without spending too much time on troubleshooting.

Much appreciated!
Mariusz.

**Comment by mgeeky** [comment]
Solved it myself. Leaving as note to others who will stumble upon same issue.

That's what worked for me:
```
pip3 uninstall msldap
pip3 install minikerberos==0.2.18
pip3 install msldap==0.3.38
pip3 install ldap3
pip3 install dnspython
```

Cheers

**Comment by zyn3rgy** [comment]
Thanks for note @mgeeky - will test soon and make the change. I appreciate you posting this.

**Comment by fsacer** [comment]
Tested as well. This is my fixed requirements.txt:

```
minikerberos==0.2.20
msldap==0.3.38
ldap3
dnspython
```
