### ISSUE TITLE
Exception not well handled when timeout

### ISSUE THREAD

**Issue by k4nfr3** [zyn3rgy/LdapRelayScan#2]
If connection fails, the script crashes.

Traceback (most recent call last):
  File "/root/LdapRelayScan/LdapRelayScan.py", line 230, in <module>
    if DoesLdapsCompleteHandshake(dc) == True:
  File "/root/LdapRelayScan/LdapRelayScan.py", line 124, in DoesLdapsCompleteHandshake
    ssl_sock.connect((dcIp, 636))
  File "/usr/lib/python3.9/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.9/ssl.py", line 1329, in _real_connect
    super().connect(addr)
socket.timeout: timed out

**Comment by zyn3rgy** [comment]
Good point - handling unreachable DCs is something that needs to included. Should be a quick fix. I'll leave this open until I implement this.

**Comment by k4nfr3** [comment]
I did a quick and dirty try catch but it's not really nice

root@kali:~/LdapRelayScan# git diff
diff --git a/LdapRelayScan.py b/LdapRelayScan.py
index fbd5f3d..a9d287b 100644
--- a/LdapRelayScan.py
+++ b/LdapRelayScan.py
@@ -121,7 +121,11 @@ def DoesLdapsCompleteHandshake(dcIp):
                             cert_reqs=ssl.CERT_OPTIONAL,
                             suppress_ragged_eofs=False,
                             do_handshake_on_connect=False)
-  ssl_sock.connect((dcIp, 636))
+  try:
+    ssl_sock.connect((dcIp, 636))
+  except Exception as e:
+      print("Error opening port 636 to " + dcIp)
+      return False
   try:
     ssl_sock.do_handshake()
     ssl_sock.close()

**Comment by zyn3rgy** [comment]
Should be resolved now: 34457166656d14dae4dd0b2aa665a57b65b03e7b
