### ISSUE TITLE
Wrong asysocks version causes ldaps_withEPA to fail

### ISSUE THREAD

**Issue by Markb1337** [zyn3rgy/LdapRelayScan#20]
**Intro**
Since some time the LdapRelayScan started failing when checking LDAPS Channel Binding. After some debugging it seems this is due to changes in 'asysocks', a dependency of LdapRelayScan. Among other things, something regarding the SSL context was changed in this dependency.

**OS and Python version**
OS: Ubuntu 20.04.1 LTS
Python: Python3.8 & Python3.9

**Replication & Fix**
This is the current state after cloning LdapRelayScan and installing the dependencies from requirements.txt:

![broken](https://github.com/zyn3rgy/LdapRelayScan/assets/15806113/4048e191-9321-48f9-97c6-c17e66835395)

Notice the error: "something went wrong during ldaps_withEPA bind: an integer is required (got type NoneType)"

Now let's swap the 'asysocks' package from version 0.2.7 (changed three weeks ago), to the older 0.2.5 version:

![fix](https://github.com/zyn3rgy/LdapRelayScan/assets/15806113/69306db5-5885-4ba5-a304-48da2b2de5a3)

And afterwards we run LdapRelayScan to verify everything is working again:

![fixed](https://github.com/zyn3rgy/LdapRelayScan/assets/15806113/371a82fc-2646-4613-9628-c469330ab75b)

So it seems we either need to hardcode the version of asysocks in the dependencies, or the codebase needs to be changed to work with the newer version of asysocks.

**Comment by zyn3rgy** [comment]
Thank you very much for the detailed report! Resolving now.
