### ISSUE TITLE
Multiple issues with docker setup on Kali on a Pi4

### ISSUE THREAD

**Issue by xalten** [zyn3rgy/LdapRelayScan#24]
I'm not super familiar with docker containers so I may be doing something horribly wrong.  Trying to get this application going in a docker on a Pi4 running the latest Kali, fully updated (2023.4)

At first, doing exactly as the github instructions state I was getting this error:

![image](https://github.com/zyn3rgy/LdapRelayScan/assets/14969781/fd1d9521-37db-4819-9d33-8bc878d7ac1b)

So I added `RUN apt install gcc -y` to the Dockerfile and re-ran.  

Then I got this error: 
![image](https://github.com/zyn3rgy/LdapRelayScan/assets/14969781/7c36fe40-0e23-498b-9dae-9ca9945a0ab8)

I googled and people were saying you need libffi-dev so I added `RUN apt install libffi-dev` to the Dockerfile as well and re-ran.

Now I'm getting this: 
![image](https://github.com/zyn3rgy/LdapRelayScan/assets/14969781/c21cc71e-a47c-4c51-8aaa-a9681cf02f48)

Feels like I'm going down a rabbit hole.  Should I be doing this a different way or is the setup I'm on just not supported?

**Comment by xalten** [comment]
per the python cryptography docs I added in build-essential libssl-dev  python3-dev cargo pkg-config to my dockerfile as well

https://github.com/pyca/cryptography/blob/main/docs/installation.rst

Everything deployed successfully.  Unfortunately though, still erroring out when I try running it.

![image](https://github.com/zyn3rgy/LdapRelayScan/assets/14969781/5b4f0e81-6698-4745-9264-f01f7276bcce)

**Comment by zyn3rgy** [comment]
The error in your most recent screenshot is associated with a downstream libcrypto problem, discussed in issue #21 

You can find a workaround mentioned there in the comments, and planning on a workaround implemented if it's not resolved on the libcrypto side before long.
