### ISSUE TITLE
String Concatenation Error

### ISSUE THREAD

**Issue by Zamanry** [zyn3rgy/LdapRelayScan#7]
I am trying to perform an anonymous check against an actual company production domain. I redacted it all here, but tried to be consistent. With out without `sudo` permissions failed. No other tools are running in the background. I can try Python 3.10 if needed. My machine is fully up-to-date in apt and has been restarted since updating just in case.

I would expect the LDAP check would fail and try the next DC until all have been checked while handling the errors appropriately.

Separate issue, but I noticed that `identified` in `~Domain Controllers identifed~` is spelled incorrectly. Also noticed the password help command talks about the username `-p password Domain username value`. Quick fixes not worth their own issue.

Let me know if you need more information.

```
┌──(kali㉿workstation)-[~/Tools/LdapRelayScan]
└─$ python './LdapRelayScan.py' -dc-ip 10.10.10.10 -method LDAPS

~Domain Controllers identifed~
  dc1.domain.tld
  dc2.domain.tld
  dc3.domain.tld
  dc4.domain.tld
  dc5.domain.tld

~Checking DCs for LDAP NTLM relay protections~
   dc1.domain.tld
UNEXPECTED ERROR: {'result': 49, 'description': 'invalidCredentials', 'dn': '', 'message': '8009030C: LdapErr: DSID-0C0906C6, comment: AcceptSecurityContext error, data 775, v3839\x00', 'referrals': None, 'saslCreds': None, 'type': 'bindResponse'}
something went wrong during ldaps_withEPA bind:can only concatenate str (not "LDAPBindException") to str

Something went wrong...
For troubleshooting:
ldapsChannelBindingAlwaysCheck - None
ldapsChannelBindingWhenSupportedCheck: None

┌──(kali㉿workstation)-[~/Tools/LdapRelayScan]
└─$ lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.1
Codename:       kali-rolling

┌──(kali㉿workstation)-[~/Tools/LdapRelayScan]
└─$ sudo proxychains pip install -r requirements.txt
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: ldap3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: msldap in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.3.30)
Requirement already satisfied: minikerberos>=0.2.14 in /usr/lib/python3/dist-packages (from msldap->-r requirements.txt (line 3)) (0.2.14)
Requirement already satisfied: asysocks>=0.0.11 in /usr/lib/python3/dist-packages (from minikerberos>=0.2.14->msldap->-r requirements.txt (line 3)) (0.1.2)
Requirement already satisfied: oscrypto>=1.2.1 in /usr/local/lib/python3.9/dist-packages (from minikerberos>=0.2.14->msldap->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: asn1crypto>=1.5.1 in /usr/local/lib/python3.9/dist-packages (from oscrypto>=1.2.1->minikerberos>=0.2.14->msldap->-r requirements.txt (line 3)) (1.5.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

┌──(kali㉿workstation)-[~/Tools/LdapRelayScan]
└─$ python -V
Python 3.9.11

┌──(kali㉿workstation)-[~/Tools/LdapRelayScan]
└─$ sudo nmap -Pn -sU -p 53 10.10.10.10 --open                                                                                                                                                                        
Starting Nmap 7.92 ( https://nmap.org ) at 2022-03-28 10:10 CDT
Nmap scan report for dc1.domain.tld (10.10.10.10)
Host is up (0.1111s latency).

PORT   STATE SERVICE
53/udp open  domain

Nmap done: 1 IP address (1 host up) scanned in 0.11 seconds
```

**Comment by zyn3rgy** [comment]
Thanks for the verbose information as well as following up, it was very helpful in determining what happened here. I think I see what was going on. In your response to an LDAPS bind attempt, you received the following error:
`{'result': 49, 'description': 'invalidCredentials', 'dn': '', 'message': '8009030C: LdapErr: DSID-0C0906C6, comment: AcceptSecurityContext error, data 775, v3839\x00', 'referrals': None, 'saslCreds': None, 'type': 'bindResponse'}`


It looks like the `data 775` portion of that response indicates the account was locked out:
https://ldapwiki.com/wiki/Common%20Active%20Directory%20Bind%20Errors

The [default value of the username parameter](https://github.com/zyn3rgy/LdapRelayScan/blob/main/LdapRelayScan.py#L174) is set to `guest`, so if you see this particular error again, simply add the `-u` parameter and set it to a random / nonexistent user in the domain should solve your issue.

**Comment by Zamanry** [comment]
So maybe we could change the default anonymous user to be random? I’d anticipate that the guest user is disabled in most domains and may or may not have been renamed. Alternatively, just write a exception check here and suggest the user use the -u flag if attempting an anonymous check. Thoughts?
